### ISSUE TITLE
Several severe bugs？

### ISSUE THREAD

**Issue by sjtuytc** [seolhokim/elevator-reinforcementlearning-application#6]
https://github.com/seolhokim/elevator-reinforcementlearning-application/blob/7c8ade6528f0ab9b44245cfc614b3db9fbc9610f/main.py#L106
One bug is in reward calculation. Why do you treat global steps as a reward?
Another severe bug is in the environment, where you put "require debug".

**Comment by seolhokim** [comment]
Hello sjtuytc, 

Thank you for interest in my repository. In this repository, global step can mean "How fast the agent finish one epoch". I wanted to see that. I guess that maybe my naming-error make you confuse. I had already checked environment, but I couldn't find. but, Agent is in debugging level.(after refactoring, It doesn't work now) I'll try to solve it quickly.

**Comment by sjtuytc** [comment]
Yes, I successfully refactored your code and made them work in multi-agent cases. I just remind you of these bugs.
